Documentation generation misc simplifications and improvements
powa-team/powa pull request #189
Opened 2024-11-21 11:09 UTC by pgiraud

2024-11-21 11:15 UTC, rjuju commented
I believe this was all generated by sphinx when the documentation was boostrapped, so I'd just keep it as is unless something breaks.

I'm not sure why you want to remove Windows friendly script? if someone wants to build the doc locally on Windows I guess they would be happier to have it.

2024-11-22 07:48 UTC, pgiraud commented
> I believe this was all generated by sphinx when the documentation was boostrapped, so I'd just keep it as is unless something breaks.

Running `sphinx-quickstart` now generates a very small Makefile. I thought it would be nice to use it to ease maintenance, ie. before adding a new target. But OK. Let's not change it.

> I'm not sure why you want to remove Windows friendly script? if someone wants to build the doc locally on Windows I guess they would be happier to have it.

OK. Sorry about that.

2024-11-22 10:54 UTC, rjuju commented
> Running sphinx-quickstart now generates a very small Makefile. I thought it would be nice to use it to ease 

Oh, I didn't know that, sorry if I missed it in the commit message.  If bootstrapping now gives a shorter makefile let's adopt it (and make it clear in the commit message).

2024-11-22 13:01 UTC, pgiraud commented
Done.

2024-11-24 05:25 UTC, rjuju commented
could you reword the first commit summary to make it more self evident, like "regenerate the makefile" or something like that? it helps when look at git blame and other short summary output.

also the 2nd and 3rd commits could be merged together as some general chores.

2024-11-24 17:45 UTC, pgiraud commented
PR updated.

2024-12-18 07:47 UTC, pgiraud commented
@rjuju can you please give this PR a new review?

2024-12-18 09:15 UTC, rjuju requested changes

2024-12-18 09:15 UTC, rjuju commented on docs/Makefile
> +serve:
could you also add an explicit "html" target?  I heavily rely on automatic tab completion and that's a very useful one.

2024-12-18 09:27 UTC, pgiraud commented on docs/Makefile
> +serve:
If we add an `html` target on our side, it will override the default one. And then other users may want other targets to be explicitly added.

2024-12-18 09:33 UTC, rjuju commented on docs/Makefile
> +serve:
I highly doubt that anyone is buliding something else than html.  But if that was the case, looking at the last ~3 years of contribution on the documentation I don't foresee a high demand for new targets:

```
$ git shortlog -sn master docs --since "2022-01-01" 
    50  Julien Rouhaud
     2  Marc Cousin
```

2024-12-18 10:01 UTC, pgiraud commented on docs/Makefile
> +serve:
Sorry, I misunderstood your first comment.

2024-12-18 10:17 UTC, rjuju approved these changes

2024-12-18 10:17 UTC, rjuju commented on docs/Makefile
> +serve:
thanks, lgtm!

2024-12-18 10:19 UTC, merged